defaults: &defaults
  max_sms_retries: 3
  max_voice_retries: 3
  sms_timeout: 5
  voice_timeout: 5
  nuntium_host: https://nuntium.instedd.org
  nuntium_account: aromero
  nuntium_app: watchfire
  nuntium_app_passwd: watchfire

development:
  <<: *defaults

test: &test
  <<: *defaults
  
staging:
  <<: *defaults
  
production:
  <<: *defaults
