defaults: &defaults
  candidate_max_sms_retries: 3
  candidate_max_phone_retries: 3
  sms_timeout: 1
  voice_timeout: 1
  nuntium_host: https://nuntium.instedd.org
  nuntium_account: aromero
  nuntium_app: watchfire
  nuntium_app_passwd: watchfire

development:
  <<: *defaults

test: &test
  <<: *defaults
  
staging:
  <<: *defaults
  
production:
  <<: *defaults
